server:
  port: 8084

spring:
  application:
    name: lab-idempotent-consumer
  threads:
    virtual:
      enabled: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      group-id: pagamento-idempotent-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.alvaro.idempotence.*"

  data:
    redis:
      timeout: 2000ms
