server:
  port: 8082

spring:
  application:
    name: lab-transactional-outbox
  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # O payload do evento já é armazenado como JSON String na Outbox
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      group-id: outbox-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
