server:
  port: 8080

spring:
  application:
    name: lab-core-banking
  threads:
    virtual:
      enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C

